### ISSUE TITLE
Office Content Type View: 8 pts

### ISSUE THREAD

**Issue by skleinfeldt** [PSUEducationalEquity/plonetheme.eeq#14]
As a user visiting an office's landing page I will see a consistent layout between offices, with standard office information displayed in the same way.

Pointed to reflect duplicating the mockup.

**Comment by alecpm** [comment]
Sample: https://beta.equity.psu.edu/a51/develop/office-home.html

**Comment by skleinfeldt** [comment]
We will very likely use Mosaic layouts for this. which could be different for every office or a layout could be saved and reused on every office. I'll keep this story open for now, but pretty sure we don't need it.
